.TH junk 1 "October 22, 2017" "version 1.0" "junk man page"

.SH NAME
junk \- moves files to junk folder where they can be reviewed before being deleted

.SH SYNOPSIS
.B junk
.RI [ 
.I file...
.R ] | [ \-l | \-r file | \-d | \-t | \-w | \-k ]
.br

.SH DESCRIPTION
This program adds a recycle bin style command to Linux called junk. Junked files are stored in a directory where they can be recovered before they are lost forever.
.SH OPTIONS
.B
.IP \-l
Displays a list of all files in the junk directory
.B
.IP \-r
Recovers the file specified as an argument
.B
.IP \-d
Interactively deletes the contents of the junk directory
.B
.IP \-t
Displays the total size of all junk directories on the system
.B
.IP \-w
Starts the watch script that lets you was file events in the junk directory
.B
.IP \-k
Kills any started watch scripts

.SH EXAMPLE
.LP
You can junk files by listing them as command arguments: 
.BR ./junk.sh 
.BI file1 
.BI file2 
.BI file3
.LP
To start the script in interactive mode, run it without any arguments.
.BR ./junk.sh
.LP
To recover a particular file specify the filename with the -r switch.
.BR ./junk.sh 
.BI \-r
.BI file1
